# Generated by Django 3.2.16 on 2023-02-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
