# Generated by Django 3.2.16 on 2023-03-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variations_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variations',
            name='stock',
        ),
    ]
