# Generated by Django 3.2.16 on 2023-03-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_variations_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
