# Generated by Django 3.2.16 on 2023-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
