# Generated by Django 3.2.16 on 2023-03-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
