# Generated by Django 3.2.16 on 2023-02-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
